MICMAC-ISM-MVC/Controllers/EOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MICMAC_ISM_MVC.Data;
using MICMAC_ISM_MVC.Models;

namespace MICMAC_ISM_MVC.Controllers
{

    //public class EOViewComponent : ViewComponent
    //{
    //    private DbContextOptions<ApplicationDbContext> db = new DbContextOptions<ApplicationDbContext>();
    //    public async Task<IViewComponentResult> InvokeAsync()
    //    {
    //        ApplicationDbContext context = new ApplicationDbContext(db);
    //        IEnumerable<ExpertOpinions> mc = await context.ExpertOpinions.Where(y => y.StructuralSelfInteractionID == id).Include(e => e.Expert).Include(e => e.SSI).ToListAsync();
    //        return View("Index", mc);
    //    }
    //}
    public class EOController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EOController(ApplicationDbContext context)
        {
            _context = context;
        }

            // GET: EO
        [HttpGet]
        public async Task<IActionResult> Data(int id)
        {
            var applicationDbContext = _context.ExpertOpinions.Where(y=>y.StructuralSelfInteractionID==id).Include(e => e.Expert).Include(e => e.SSI);
            ViewData["SSIID"] = id;
            return PartialView("Index", await applicationDbContext.ToListAsync());
        }

        // GET: EO/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ExpertOpinions == null)
            {
                return NotFound();
            }

            var expertOpinions = await _context.ExpertOpinions
                .Include(e => e.Expert)
                .Include(e => e.SSI)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (expertOpinions == null)
            {
                return NotFound();
            }

            return View(expertOpinions);
        }

        // GET: EO/Create
        public IActionResult Create(int id)
        {
            List<String> interaction = new List<String>() { "V", "A", "X", "O" };
            var ssi = _context.StructuralSelfInteractions.Find(id);
            var featureA = _context.Features.Find(ssi.FeatureAID);
            var featureB = _context.Features.Find(ssi.FeatureBID);
            ViewData["f1"] = featureA.Code;
            ViewData["f2"] = featureB.Code;
            var project = _context.ProjectIdentitiy.Find(featureA.ProjectID);
            ViewData["ExpertID"] = new SelectList(_context.Experts.Where(y=>y.ProjectID==project.ID), "ID", "Name");
            ViewData["StructuralSelfInteractionID"] = id;
            ViewData["InteractionType"] = new SelectList(interaction);
            return View();
        }

        // POST: EO/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ExpertID,StructuralSelfInteractionID,Opinion,InteractionType")] ExpertOpinions expertOpinions)
        {
            expertOpinions.ID = 0;
            var ssi = _context.StructuralSelfInteractions.Find(expertOpinions.StructuralSelfInteractionID);
            var featureA = _context.Features.Find(ssi.FeatureAID);
            var featureB = _context.Features.Find(ssi.FeatureBID);
                _context.ExpertOpinions.Add(expertOpinions);
                await _context.SaveChangesAsync();
                return RedirectToAction("CreateInteraction","Features", new { id=featureA.ID, id2=featureB.ID });
        }

        // GET: EO/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ExpertOpinions == null)
            {
                return NotFound();
            }

            var expertOpinions = await _context.ExpertOpinions.FindAsync(id);
            if (expertOpinions == null)
            {
                return NotFound();
            }
            ViewData["ExpertID"] = new SelectList(_context.Experts, "ID", "ID", expertOpinions.ExpertID);
            ViewData["StructuralSelfInteractionID"] = new SelectList(_context.StructuralSelfInteractions, "ID", "ID", expertOpinions.StructuralSelfInteractionID);
            return View(expertOpinions);
        }

        // POST: EO/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ExpertID,StructuralSelfInteractionID,InteractionType")] ExpertOpinions expertOpinions)
        {
            if (id != expertOpinions.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(expertOpinions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpertOpinionsExists(expertOpinions.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExpertID"] = new SelectList(_context.Experts, "ID", "ID", expertOpinions.ExpertID);
            ViewData["StructuralSelfInteractionID"] = new SelectList(_context.StructuralSelfInteractions, "ID", "ID", expertOpinions.StructuralSelfInteractionID);
            return View(expertOpinions);
        }

        // GET: EO/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ExpertOpinions == null)
            {
                return NotFound();
            }

            var expertOpinions = await _context.ExpertOpinions
                .Include(e => e.Expert)
                .Include(e => e.SSI)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (expertOpinions == null)
            {
                return NotFound();
            }

            return View(expertOpinions);
        }

        // POST: EO/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ExpertOpinions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ExpertOpinions'  is null.");
            }
            var expertOpinions = await _context.ExpertOpinions.FindAsync(id);
            if (expertOpinions != null)
            {
                _context.ExpertOpinions.Remove(expertOpinions);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpertOpinionsExists(int id)
        {
          return (_context.ExpertOpinions?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

MICMAC-ISM-MVC/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MICMAC_ISM_MVC.Data;
using MICMAC_ISM_MVC.Models;
using System.Drawing.Drawing2D;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Authorization;

namespace MICMAC_ISM_MVC.Controllers
{
    [Authorize]
    public class FeaturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FeaturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Features
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity)
                .Where(m => m.ProjectID == id);
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult CreateInteraction(int id, int id2)
        {
            ViewData["featureAID"] = id;
            ViewData["featureBID"] = id2;
            var featureA = _context.Features.Find(id);
            var featureB = _context.Features.Find(id2);
            ViewData["Title"] = "Set interactions between " + featureA.Code + " and " + featureB.Code;
            //ViewData["Subtitle"] = featureA.ProjectIdentity.Title;
            List <String> interaction = new List<String>() { "V", "A", "X", "O" };
            ViewData["ProjectID"] = featureA.ProjectID;
            ViewData["ExistingStatus"] = _context.StructuralSelfInteractions.Where(y => y.FeatureAID == id && y.FeatureBID == id2).Count() != 0;
            if (_context.StructuralSelfInteractions.Where(y => y.FeatureAID==id&&y.FeatureBID == id2).Count() != 0)
            {
                var existing = _context.StructuralSelfInteractions.Where(y => y.FeatureAID == id && y.FeatureBID == id2).First();
                //ViewData["SelectedInteraction"] = existing.InteractionType;
                ViewData["SSIID"] = existing.ID;
                ViewData["InteractionType"] = new SelectList(interaction,existing.InteractionType);
                return View();
            }
            else
            {
                ViewData["SSIID"] = 1;
                var SelectedInteraction = "V";
                ViewData["InteractionType"] = new SelectList(interaction,SelectedInteraction);
                return View();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateInteraction([Bind("ID,FeatureAID,FeatureBID,InteractionType")] StructuralSelfInteraction ssi)
        {
            //if (ModelState.IsValid)
            //{
            var f = _context.Features.Find(ssi.FeatureAID);
            if (ssi.InteractionType=="V"|| ssi.InteractionType == "A"|| ssi.InteractionType == "X"||ssi.InteractionType == "O")
            {
                if (_context.StructuralSelfInteractions.Where(y => y.FeatureAID == ssi.FeatureAID && y.FeatureBID == ssi.FeatureBID).Count() != 0)
                {
                    _context.StructuralSelfInteractions.Where(y => y.FeatureAID == ssi.FeatureAID && y.FeatureBID == ssi.FeatureBID).First().InteractionType = ssi.InteractionType;
                    _context.SaveChanges();
                    return RedirectToAction(nameof(SSI), new { id = f.ProjectID });
                }
                else
                {
                    ssi.ID = 0;
                    _context.StructuralSelfInteractions.Add(ssi);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(SSI), new { id = f.ProjectID });
                }
            }

            else
            {
                ViewData["featureAID"] = ssi.FeatureAID;
                ViewData["featureBID"] = ssi.FeatureBID;
                List<String> interaction = new List<String>() { "V", "A", "X", "O" };
                ViewData["InteractionType"] = new SelectList(interaction);
                return View(ssi);
            }

        }

        // GET: Features
        public async Task<IActionResult> SSI(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y=>y.SSI)
                .Where(m => m.ProjectID == id);
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> IRM(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y => y.IRM)
                .Where(m => m.ProjectID == id);
            ViewData["status"] = _context.InitialReachabilityMatrix.Where(y => y.FeatureA.ProjectID == id).Count()!=0;
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult GenerateIRM(int id)
        {
            List<InitialReachabilityMatrix> data = new List<InitialReachabilityMatrix>();
            var features = _context.Features.Where(y => y.ProjectID == id).ToList();
            var applicationDbContext = _context.StructuralSelfInteractions.Where(y=>y.FeatureA.ProjectID == id).ToList();
            foreach(var x in features)
            {
                var testcount = applicationDbContext.Where(y => y.FeatureAID == x.ID).Count() + applicationDbContext.Where(y => y.FeatureBID == x.ID).Count();
                if (testcount != features.Count() - 1)
                {
                    return RedirectToAction(nameof(IRM), new { id = id });
                }
                else
                {
                    testcount = testcount;
                }
            }
            foreach (var matrix in applicationDbContext)
            {
                if (matrix.InteractionType == "V")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 1
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 0
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "A")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 0
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 1
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "O")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 0
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 0
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "X")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 1
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 1
                    };
                    data.Add(datapoint_2);
                }
                else
                {
                    var test = 0;
                }
            }
            foreach(var item in features)
            {
                InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                {
                    FeatureAID = item.ID,
                    FeatureBID = item.ID,
                    IRM = 1
                };
                data.Add(datapoint_1);
            }
            _context.InitialReachabilityMatrix.AddRange(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(IRM), new { id=id });
        }

        public async Task<IActionResult> FRM(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y => y.FRM).Include(y => y.TN).Include(y=>y.Coordinate)
                .Where(m => m.ProjectID == id);

MICMAC-ISM-MVC/Views/Features/Create.cshtml
@model MICMAC_ISM_MVC.Models.Features

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Features</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VariableName" class="control-label"></label>
                <input asp-for="VariableName" class="form-control" />
                <span asp-validation-for="VariableName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class ="form-control" asp-items="ViewBag.ProjectID"></select>
            </div>*@

            <input type="hidden" asp-for="ProjectID" value="@ViewBag.ProjectID" />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MICMAC-ISM-MVC/Views/Features/CreateInteraction.cshtml
@model MICMAC_ISM_MVC.Models.StructuralSelfInteraction


<h1>@ViewBag.Title</h1>
@*<h4>@ViewBag.Subtitle</h4>*@

<hr />

<div class="alert alert-primary" role="alert">
    <strong>Notes:</strong>
    <ul>
        <li><strong>V</strong>-variable i will influence variable j;</li>
        <li><strong>A</strong>-variable j will influence variable i;</li>
        <li><strong>X</strong>-variables i and j will influence each other; and</li>
        <li><strong>O</strong>-variables i and j are not related to each other</li>
    </ul>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateInteraction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="InteractionType" class="control-label"></label>
                <select asp-for="InteractionType" class ="form-control" asp-items="ViewBag.InteractionType"></select>
            </div>

            <input type="hidden" asp-for="FeatureAID" value="@ViewBag.FeatureAID" />
            <input type="hidden" asp-for="FeatureBID" value="@ViewBag.FeatureBID" />

            <div class="form-group">
                <input type="submit" value="Save Interaction" class="btn btn-primary" /> <a asp-action="SSI" asp-route-id="@ViewBag.ProjectID" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </div>
</div>

<hr />
<h5>Expert Opinions</h5>
@if (ViewBag.ExistingStatus)
{
    <div id="expertOpinionContainer"></div>
    <script>
        $.get('@Url.Action("Data", "EO")' +'/'+ '@ViewBag.SSIID', function (content) {
            $("#expertOpinionContainer").html(content);
        });
    </script>
}
else
{
    <p>No expert opinions recorded.</p>
}

@*<div>
    <a asp-action="SSI" asp-route="@ViewBag.ProjectID">Back to SSI Matrix</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MICMAC-ISM-MVC/Views/Features/Delete.cshtml
@model MICMAC_ISM_MVC.Models.Features

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Features</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VariableName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VariableName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectIdentity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectIdentity.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MICMAC-ISM-MVC/Views/Features/Details.cshtml
@model MICMAC_ISM_MVC.Models.Features

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Features</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VariableName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VariableName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectIdentity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectIdentity.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

@*@foreach(var item in Model.SSI)
{
    <p>@item.InteractionType</p>
}*@

MICMAC-ISM-MVC/Views/Features/Edit.cshtml
@model MICMAC_ISM_MVC.Models.Features

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Features</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="ProjectID" />
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VariableName" class="control-label"></label>
                <input asp-for="VariableName" class="form-control" />
                <span asp-validation-for="VariableName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class="form-control" asp-items="ViewBag.ProjectID"></select>
                <span asp-validation-for="ProjectID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MICMAC-ISM-MVC/Views/Features/HierarchicalModel.cshtml
@{
    ViewData["Title"] = "ISM-based Hierarchical Model";
}

<h1>@ViewBag.Title</h1>
<h5>@ViewBag.Project</h5>

<pre class="mermaid">
    flowchart BT
    @Html.Raw(ViewBag.datapoints)
</pre>

<hr />
@{
    var parms = new Dictionary<string, string>
                {
                { "id", ViewBag.ProjectID.ToString() },
                { "source", "HierarchicalModel" }
                };
}
<a asp-action="ClearAnalysisData" asp-all-route-data="parms" class="btn btn-sm btn-danger">Clear Analysis Data</a>

<script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
      mermaid.initialize({ startOnLoad: true });
    </script>

MICMAC-ISM-MVC/Views/Features/IRM.cshtml
@model IEnumerable<MICMAC_ISM_MVC.Models.Features>

@{
    ViewData["Title"] = "Initial Reachability Matrix (IRM)";
    ViewData["Subtitle"] = ViewBag.Project;
}



<h1>@ViewBag.Title</h1>
<h5>@ViewBag.Subtitle</h5>

@if (ViewBag.status == false)
{
    <a asp-action="GenerateIRM" asp-route-id="@ViewBag.ProjectID" class="btn btn-success">Generate Initial Reachability Matrix</a>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VariableName)
            </th>
            @foreach (var item in Model.OrderBy(y => y.Code))
            {
                <th>
                    @item.Code
                </th>
            }
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.OrderBy(y => y.Code))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VariableName)
                </td>

                @foreach (var item2 in Model.OrderBy(y => y.Code))
                {
                    if (item.IRM.Where(x => x.FeatureAID == item.ID && x.FeatureBID == item2.ID).Count() != 0)
                    {
                        <td>@item.IRM.Where(x => x.FeatureAID == item.ID && x.FeatureBID == item2.ID).First().IRM</td>
                    }
                    else
                    {

                        <td>??</td>
                    }
                }
            </tr>
        }
    </tbody>
</table>
<hr />
@{
    var parms = new Dictionary<string, string>
                {
                { "id", ViewBag.ProjectID.ToString() },
                { "source", "IRM" }
                };
}
<a asp-action="ClearAnalysisData" asp-all-route-data="parms" class="btn btn-sm btn-danger">Clear Analysis Data</a>

MICMAC-ISM-MVC/Views/Features/Index.cshtml
@model IEnumerable<MICMAC_ISM_MVC.Models.Features>

@{
    ViewData["Title"] = "List of Variables Analyzed"; 
    ViewData["Subtitle"] = ViewBag.Project;
}

<h1>@ViewBag.Title</h1>
<h5>@ViewBag.Subtitle</h5>

<p>
    <a asp-action="Create" asp-route-id="@ViewBag.ProjectID" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VariableName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VariableName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>