MICMAC-ISM-MVC/Controllers/ExpertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MICMAC_ISM_MVC.Data;
using MICMAC_ISM_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace MICMAC_ISM_MVC.Controllers
{
    [Authorize]
    public class ExpertsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExpertsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Experts
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Experts.Include(f => f.ProjectIdentity)
                .Where(m => m.ProjectID == id);
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Experts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Experts == null)
            {
                return NotFound();
            }

            var experts = await _context.Experts
                .Include(e => e.ProjectIdentity)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (experts == null)
            {
                return NotFound();
            }

            return View(experts);
        }

        // GET: Experts/Create
        public IActionResult Create(int id)
        {
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View();
        }

        // POST: Experts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,Organization,ProjectID")] Experts experts)
        {
            experts.ID = 0;    
            _context.Experts.Add(experts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id=experts.ProjectID });

        }

        // GET: Experts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Experts == null)
            {
                return NotFound();
            }

            var experts = await _context.Experts.FindAsync(id);
            if (experts == null)
            {
                return NotFound();
            }
            ViewData["ProjectID"] = experts.ProjectID;
            return View(experts);
        }

        // POST: Experts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,Organization,ProjectID")] Experts experts)
        {
            if (id != experts.ID)
            {
                return NotFound();
            }

                try
                {
                    _context.Update(experts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpertsExists(experts.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));

        }

        // GET: Experts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Experts == null)
            {
                return NotFound();
            }

            var experts = await _context.Experts
                .Include(e => e.ProjectIdentity)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (experts == null)
            {
                return NotFound();
            }

            return View(experts);
        }

        // POST: Experts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Experts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Experts'  is null.");
            }
            var experts = await _context.Experts.FindAsync(id);
            if (experts != null)
            {
                _context.Experts.Remove(experts);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpertsExists(int id)
        {
          return (_context.Experts?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

MICMAC-ISM-MVC/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MICMAC_ISM_MVC.Data;
using MICMAC_ISM_MVC.Models;
using System.Drawing.Drawing2D;
using System.Runtime.CompilerServices;
using Microsoft.AspNetCore.Authorization;

namespace MICMAC_ISM_MVC.Controllers
{
    [Authorize]
    public class FeaturesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FeaturesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Features
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity)
                .Where(m => m.ProjectID == id);
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult CreateInteraction(int id, int id2)
        {
            ViewData["featureAID"] = id;
            ViewData["featureBID"] = id2;
            var featureA = _context.Features.Find(id);
            var featureB = _context.Features.Find(id2);
            ViewData["Title"] = "Set interactions between " + featureA.Code + " and " + featureB.Code;
            //ViewData["Subtitle"] = featureA.ProjectIdentity.Title;
            List <String> interaction = new List<String>() { "V", "A", "X", "O" };
            ViewData["ProjectID"] = featureA.ProjectID;
            ViewData["ExistingStatus"] = _context.StructuralSelfInteractions.Where(y => y.FeatureAID == id && y.FeatureBID == id2).Count() != 0;
            if (_context.StructuralSelfInteractions.Where(y => y.FeatureAID==id&&y.FeatureBID == id2).Count() != 0)
            {
                var existing = _context.StructuralSelfInteractions.Where(y => y.FeatureAID == id && y.FeatureBID == id2).First();
                //ViewData["SelectedInteraction"] = existing.InteractionType;
                ViewData["SSIID"] = existing.ID;
                ViewData["InteractionType"] = new SelectList(interaction,existing.InteractionType);
                return View();
            }
            else
            {
                ViewData["SSIID"] = 1;
                var SelectedInteraction = "V";
                ViewData["InteractionType"] = new SelectList(interaction,SelectedInteraction);
                return View();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateInteraction([Bind("ID,FeatureAID,FeatureBID,InteractionType")] StructuralSelfInteraction ssi)
        {
            //if (ModelState.IsValid)
            //{
            var f = _context.Features.Find(ssi.FeatureAID);
            if (ssi.InteractionType=="V"|| ssi.InteractionType == "A"|| ssi.InteractionType == "X"||ssi.InteractionType == "O")
            {
                if (_context.StructuralSelfInteractions.Where(y => y.FeatureAID == ssi.FeatureAID && y.FeatureBID == ssi.FeatureBID).Count() != 0)
                {
                    _context.StructuralSelfInteractions.Where(y => y.FeatureAID == ssi.FeatureAID && y.FeatureBID == ssi.FeatureBID).First().InteractionType = ssi.InteractionType;
                    _context.SaveChanges();
                    return RedirectToAction(nameof(SSI), new { id = f.ProjectID });
                }
                else
                {
                    ssi.ID = 0;
                    _context.StructuralSelfInteractions.Add(ssi);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(SSI), new { id = f.ProjectID });
                }
            }

            else
            {
                ViewData["featureAID"] = ssi.FeatureAID;
                ViewData["featureBID"] = ssi.FeatureBID;
                List<String> interaction = new List<String>() { "V", "A", "X", "O" };
                ViewData["InteractionType"] = new SelectList(interaction);
                return View(ssi);
            }

        }

        // GET: Features
        public async Task<IActionResult> SSI(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y=>y.SSI)
                .Where(m => m.ProjectID == id);
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> IRM(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y => y.IRM)
                .Where(m => m.ProjectID == id);
            ViewData["status"] = _context.InitialReachabilityMatrix.Where(y => y.FeatureA.ProjectID == id).Count()!=0;
            ViewData["ProjectID"] = id;
            ViewData["Project"] = _context.ProjectIdentitiy.Find(id).Title;
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult GenerateIRM(int id)
        {
            List<InitialReachabilityMatrix> data = new List<InitialReachabilityMatrix>();
            var features = _context.Features.Where(y => y.ProjectID == id).ToList();
            var applicationDbContext = _context.StructuralSelfInteractions.Where(y=>y.FeatureA.ProjectID == id).ToList();
            foreach(var x in features)
            {
                var testcount = applicationDbContext.Where(y => y.FeatureAID == x.ID).Count() + applicationDbContext.Where(y => y.FeatureBID == x.ID).Count();
                if (testcount != features.Count() - 1)
                {
                    return RedirectToAction(nameof(IRM), new { id = id });
                }
                else
                {
                    testcount = testcount;
                }
            }
            foreach (var matrix in applicationDbContext)
            {
                if (matrix.InteractionType == "V")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 1
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 0
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "A")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 0
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 1
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "O")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 0
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 0
                    };
                    data.Add(datapoint_2);
                }
                else if (matrix.InteractionType == "X")
                {
                    InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureAID,
                        FeatureBID = matrix.FeatureBID,
                        IRM = 1
                    };
                    data.Add(datapoint_1);

                    InitialReachabilityMatrix datapoint_2 = new InitialReachabilityMatrix()
                    {
                        FeatureAID = matrix.FeatureBID,
                        FeatureBID = matrix.FeatureAID,
                        IRM = 1
                    };
                    data.Add(datapoint_2);
                }
                else
                {
                    var test = 0;
                }
            }
            foreach(var item in features)
            {
                InitialReachabilityMatrix datapoint_1 = new InitialReachabilityMatrix()
                {
                    FeatureAID = item.ID,
                    FeatureBID = item.ID,
                    IRM = 1
                };
                data.Add(datapoint_1);
            }
            _context.InitialReachabilityMatrix.AddRange(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(IRM), new { id=id });
        }

        public async Task<IActionResult> FRM(int id)
        {
            var applicationDbContext = _context.Features.Include(f => f.ProjectIdentity).Include(y => y.FRM).Include(y => y.TN).Include(y=>y.Coordinate)
                .Where(m => m.ProjectID == id);

MICMAC-ISM-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MICMAC-ISM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MICMAC_ISM_MVC.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MICMAC-ISM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Projects" asp-action="Details" asp-route-id="@ViewBag.ProjectID">Project Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="Index" asp-route-id="@ViewBag.ProjectID">Feature List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Experts" asp-action="Index" asp-route-id="@ViewBag.ProjectID">Experts Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="SSI" asp-route-id="@ViewBag.ProjectID">SSI</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="IRM" asp-route-id="@ViewBag.ProjectID">IRM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="FRM" asp-route-id="@ViewBag.ProjectID">FRM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="Partition" asp-route-id="@ViewBag.ProjectID">Partition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Features" asp-action="HierarchicalModel" asp-route-id="@ViewBag.ProjectID">Hierarchical Model</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MICMAC-ISM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MICMAC-ISM-MVC/Views/Shared/_LayoutGeneral.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MICMAC-ISM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MICMAC_ISM_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MICMAC-ISM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MICMAC-ISM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>